version: 2.1
jobs:
  build:
    working_directory: ~/monitor-progress-backend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: update-npm
         command: 'sudo npm install -g npm@latest'
      - run:
         name: NPM install
         command: npm install
      - save_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
           - ./node_module
      - run:
          name: Build Typescript
          command: npm run tsc
      - run:
          name: Log In into Dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build docker image
          command: docker build -t apociejowski/monitoring-progress-backend:$CIRCLE_BUILD_NUM .
      - run:
           name: Push docker image
           command: docker push apociejowski/monitoring-progress-backend:$CIRCLE_BUILD_NUM
      - add_ssh_keys:
          fingerprints:
            - $PRIVATE_KEY_FINGERPRINT
      - run:
          name: Add master node to known hosts
          command: 'ssh-keyscan $MASTER_SERVER_URL >> ~/.ssh/known_hosts'
      - run:
          name: Send deployment configuration
          command: 'scp -i ~/.ssh/$PRIVATE_KEY_FILENAME -r ./build valverde@$MASTER_SERVER_URL:'
