version: 2.1
jobs:
  build:
    working_directory: ~/monitor-progress-backend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
         name: update-npm
         command: 'sudo npm install -g npm@latest'
      - run:
         name: npm-install
         command: npm install
      - save_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
           - ./node_module
      - run:
          name: build-tsc
          command: npm run tsc
      - run:
          name: login-dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: docker-build
          command: docker build -t apociejowski/monitoring-progress-backend .
      - run:
           name: docker-push
           command: docker push apociejowski/monitoring-progress-backend
      - add_ssh_keys:
          fingerprints:
            - "52:72:cc:59:c2:43:da:3f:18:b8:c5:92:de:89:ab:28"
      - run:
          name: send-artifacts2
          command: 'cat ~/.ssh/known_hosts'
      - run:
          name: send-artifacts1
          command: 'ssh-keyscan 188.68.242.244 >> ~/.ssh/known_hosts'
      - run:
          name: send-artifacts2
          command: 'cat ~/.ssh/known_hosts'
      - run:
          name: send-artifacts
          command: 'scp -i ~/.ssh/id_rsa_5272cc59c243da3f18b8c592de89ab28 -r ./build valverde@188.68.242.244:'
