apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-michal
  namespace: "monitoring-progress-michal"
spec:
  rules:
    - host: monitoring-progress-michal-couchdb.valverde.duckdns.org
      http:
        paths:
          - backend:
              serviceName: couchdb-michal
              servicePort: 5984
    - host: monitoring-progress-michal-backend.valverde.duckdns.org
      http:
        paths:
          - backend:
              serviceName: nodejs-backend-michal
              servicePort: 3000
    - host: monitoring-progress-michal.valverde.duckdns.org
      http:
        paths:
          - backend:
              serviceName: app-frontend-michal
              servicePort: 80
