apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-backend
  namespace: "monitoring-progress"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
        - name: nodejs-backend
          image: node:12.16.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
