apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx"
  namespace: "monitoring-progress"
spec:
  rules:
    - host: couchdb.apociejowski.pl
      http:
        paths:
          - backend:
              serviceName: couchdb
              servicePort: 5984
    - host: monitoring-progress-backend.apociejowski.pl
      http:
        paths:
          - backend:
              serviceName: nodejs-backend
              servicePort: 3000
    - host: monitoring-progress.apociejowski.pl
      http:
        paths:
          - backend:
              serviceName: app-frontend
              servicePort: 80
